import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBell, faBookmark, faBookOpen, faChevronRight, faClock, faMagnifyingGlass, faPenToSquare, faUserPlus } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";
import { BottomNav, SiteFooter, SiteHeader } from "./components/site-shell";
import { FavoriteButton } from "./components/recipe-actions";
import { RecipeThumbnail } from "./components/recipe-thumbnail";
import { getCategories, getHomeNotices, getPopularRecipes, getPublicRecipes, getViewer, type RecipeData } from "../lib/recipes";

function RecipeCards({ recipes }: { recipes: RecipeData[] }) {
  return <div className="recipe-grid">{recipes.map((recipe) => <article className="recipe-card" key={recipe.id}><Link className="recipe-visual" href={`/recipes/${recipe.id}`}><RecipeThumbnail imageUrl={recipe.imageUrl} title={recipe.title} sizes="(max-width: 600px) 100vw, (max-width: 860px) 50vw, 33vw" /></Link><div className="recipe-body"><div className="recipe-meta"><span><FontAwesomeIcon icon={faClock} />{recipe.cookingTime ? `${recipe.cookingTime}分` : "時間未設定"}</span><span><FontAwesomeIcon icon={faBookmark} />{recipe.saveCount}</span></div><h3><Link href={`/recipes/${recipe.id}`}>{recipe.title}</Link></h3><div className="recipe-tags" aria-label={`${recipe.title}の分類`}><span className="recipe-tag">{recipe.category}</span>{recipe.tags.slice(0, 2).map((tag) => <span className="recipe-tag" key={tag}>{tag}</span>)}</div><div className="recipe-card-actions"><Link className="secondary-button" href={`/recipes/${recipe.id}`}>レシピを見る</Link>{recipe.ownerUserId !== recipe.viewerUserId ? <FavoriteButton recipeId={recipe.id} recipeName={recipe.title} initialFavorite={recipe.favorite} /> : null}</div></div></article>)}</div>;
}

export default async function HomePage() {
  const [newResult, popularResult, categoriesResult, noticesResult, viewerResult] = await Promise.allSettled([getPublicRecipes(3), getPopularRecipes(3), getCategories(), getHomeNotices(3), getViewer()]);
  const newest = newResult.status === "fulfilled" ? newResult.value : [];
  const popular = popularResult.status === "fulfilled" ? popularResult.value : [];
  const categories = categoriesResult.status === "fulfilled" ? categoriesResult.value.slice(0, 6) : [];
  const notices = noticesResult.status === "fulfilled" ? noticesResult.value : [];
  const viewer = viewerResult.status === "fulfilled" ? viewerResult.value : null;
  return <div className="app-shell"><SiteHeader /><main id="top">
    <section className="home-hero" aria-labelledby="home-title"><p>毎日の「また作りたい」を、ひとつの場所へ。</p><h1 id="home-title">いつもの味を、<br />迷わず作れるレシピ帳</h1><form className="recipe-search" action="/recipes" role="search"><div className="search-field"><FontAwesomeIcon className="search-icon" icon={faMagnifyingGlass} /><label className="sr-only" htmlFor="recipe-query">レシピを検索</label><input id="recipe-query" name="q" type="search" placeholder="料理名・材料・タグで探す" /></div><button type="submit">検索</button></form></section>
    <section className="start-panel" aria-labelledby="start-title"><div className="section-heading"><div><h2 id="start-title">今日は、何から始める？</h2></div><p>{viewer ? "登録したレシピや保存したレシピへ、すぐ移動できます。" : "公開レシピを探すか、無料登録して自分のレシピ帳を始められます。"}</p></div><div className="quick-grid">{viewer ? <><Link className="quick-action quick-action-primary" href="/recipes/new"><span className="quick-icon"><FontAwesomeIcon icon={faPenToSquare} /></span><span><strong>レシピを登録</strong><small>分量や手順を自分用に残す</small></span><FontAwesomeIcon icon={faChevronRight} /></Link><Link className="quick-action" href="/mypage/recipes"><span className="quick-icon"><FontAwesomeIcon icon={faBookOpen} /></span><span><strong>マイレシピ</strong><small>登録・保存したレシピを見る</small></span><FontAwesomeIcon icon={faChevronRight} /></Link></> : <><Link className="quick-action quick-action-primary" href="/signup"><span className="quick-icon"><FontAwesomeIcon icon={faUserPlus} /></span><span><strong>無料でレシピ帳を作る</strong><small>保存・人数換算・自分用コピーが使えます</small></span><FontAwesomeIcon icon={faChevronRight} /></Link><Link className="quick-action" href="/recipes"><span className="quick-icon"><FontAwesomeIcon icon={faBookOpen} /></span><span><strong>公開レシピを探す</strong><small>材料や調理時間で絞り込む</small></span><FontAwesomeIcon icon={faChevronRight} /></Link></>}</div></section>
    <section className="recipe-section" aria-labelledby="new-title"><div className="section-heading section-heading-inline"><div><h2 id="new-title">新着レシピ</h2><p>最近公開された、みんなのレシピです。</p></div><Link className="text-link" href="/recipes?sort=new">すべて見る <FontAwesomeIcon icon={faChevronRight} /></Link></div>{newest.length ? <RecipeCards recipes={newest} /> : <p className="section-empty">新着レシピを読み込めませんでした。</p>}</section>
    <section className="recipe-section home-section-tinted" aria-labelledby="popular-title"><div className="section-heading section-heading-inline"><div><h2 id="popular-title">よく保存されているレシピ</h2><p>あとでもう一度作りたいと選ばれたレシピです。</p></div><Link className="text-link" href="/recipes?sort=saves">ランキングを見る <FontAwesomeIcon icon={faChevronRight} /></Link></div>{popular.length ? <RecipeCards recipes={popular} /> : <p className="section-empty">人気レシピを読み込めませんでした。</p>}</section>
    <section className="home-category-section" aria-labelledby="category-title"><div className="section-heading section-heading-inline"><div><h2 id="category-title">カテゴリから探す</h2><p>今作りたい料理の種類から選べます。</p></div></div><div className="home-category-grid">{categories.map((category) => <Link key={category.id} href={`/recipes?category=${category.id}`}>{category.name}<FontAwesomeIcon icon={faChevronRight} /></Link>)}</div></section>
    <section className="pantry-section" aria-labelledby="pantry-title"><div className="pantry-copy"><h2 id="pantry-title">冷蔵庫にあるものから探す</h2><p>材料をひとつ選ぶだけで、公開レシピを絞り込めます。</p><Link className="pantry-link" href="/ingredients">材料をもっと見る <FontAwesomeIcon icon={faChevronRight} /></Link></div><div className="ingredient-tags" aria-label="食材から検索">{["鶏肉", "豚肉", "たまご", "豆腐", "キャベツ", "なす"].map((item) => <Link key={item} href={`/recipes?ingredient=${encodeURIComponent(item)}`}>{item}</Link>)}</div></section>
    <section className="home-notices" aria-labelledby="notice-title"><div className="section-heading section-heading-inline"><div><h2 id="notice-title"><FontAwesomeIcon icon={faBell} /> お知らせ</h2></div><Link className="text-link" href="/notices">すべて見る <FontAwesomeIcon icon={faChevronRight} /></Link></div>{notices.length ? <div>{notices.map((notice) => <Link key={notice.id} href={`/notices/${notice.id}`}><time>{notice.publish_at ? new Date(notice.publish_at).toLocaleDateString("ja-JP") : ""}</time><strong>{notice.title}</strong><FontAwesomeIcon icon={faChevronRight} /></Link>)}</div> : <p className="section-empty">現在お知らせはありません。</p>}</section>
  </main><SiteFooter /><BottomNav /></div>;
}
